name: '🚀 publish NPM package'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: 🔧 install dependencies
        run: npm ci

  release:
    name: 🚀 publish NPM package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 publish
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
