name: '🚀 Release packges to gpr and npm'

on:
  release:
    types: [created]

jobs:
  build:
    name: 🔨 build
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: 🔧 install dependencies
        run: npm ci

  publish-npm:
    name: 🚀 publish NPM package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: 🔧 install dependencies
        run: npm ci
      - name: 🚀 publish
        run: |
          # Change publish registry
          echo "$(jq '.publishConfig.registry = "https://registry.npmjs.org"' package.json)" > package.json
          # Publish package
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  
  publish-gpr:
    name: 📦 publish to GitHub package registry
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: 🔧 install dependencies
        run: npm ci
      - name: publish to GitHub registry
        run: |
          # Change publish registry
          echo "$(jq '.pubhlishConfig.registry = "https://npm.pkg.github.com"' package.json )" > package.json
          # Add organisation scope to package name
          echo #(jq '.name = "@DefaultsBotDevelopment/DBD-Tools"' package.json") > package.json
          # Publish the package
          npm publish --@DefaultsBotDevelopment:registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
