name: '🚀 Release packages to gpr and npm'

on:
  release:
    types: [created]

jobs:
  build:
    name: 🔨 build
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: 🔧 install dependencies
        run: npm ci

  publish-gpr:
    name: 📦 publish to GitHub package registry
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@DefaultsBotDevelopment'
      - name: 🔧 install dependencies
        run: npm ci
      - name: 📦 publish to GitHub registry
        run: |
          echo "https://npm.pkg.github.com/DefaultsBotDevelopment" >> ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}
